name: Run Tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: |
          npm ci --no-audit --ignore-scripts
          npm audit fix --dry-run

      - name: Run Unit Tests
        run: npx hardhat test

      - name: Run Coverage Report
        run: npx hardhat coverage